<?php

declare(strict_types=1);

namespace MathParser;

/*
* @package     Parsing
* @author      Frank Wikström <frank@mossadal.se>
* @author      Horse Luke <horseluke@126.com>
* @copyright   2015 Frank Wikström
* @license     http://www.opensource.org/licenses/lgpl-license.php LGPL
*
*/

use MathParser\Lexing\{Lexer, Token};
use MathParser\Parsing\Nodes\Node;
use MathParser\Parsing\Parser;

abstract class AbstractMathParser {
	/** StdMathLexer $lexer instance of Lexer used for tokenizing */
	protected Lexer $lexer;

	/** Parser $parser instance of Parsed used for the actual parsing */
	protected Parser $parser;

	/**
	 * List of tokens generated by the Lexer
	 *
	 * @var list<Token>
	 */
	protected array $tokens;

	/** Node $tree AST generated by the parser */
	protected Node $tree;

	public function setSimplifying(bool $flag): void {
		$this->parser->setSimplifying($flag);
	}

	/** Return Lexer */
	public function getLexer(): Lexer {
		return $this->lexer;
	}

	/** Return Parser */
	public function getParser(): Parser {
		return $this->parser;
	}

	/**
	 * Return the token list for the last parsed expression.
	 *
	 * @return Token[]
	 */
	public function getTokenList(): array {
		return $this->tokens;
	}

	/** Return the AST of the last parsed expression. */
	public function getTree(): Node {
		return $this->tree;
	}

	/** Replace Lexer */
	public function replaceLexer(Lexer $lexer): void {
		$this->lexer = $lexer;
	}

	/** Replace Parser */
	public function replaceParser(Parser $parser): void {
		$this->parser = $parser;
	}

	abstract public function parse(string $text): Node;
}
