name: Check static code analysis
on: [push, pull_request]

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1.17
          coverage: none
      - name: Run tests
        shell: bash
        run: |
          composer install -q
          composer dumpautoload
          "$(composer config vendor-dir)/bin/phpunit" --stop-on-failure -c phpunit.xml